# Librería `numpy`

NumPy, short for Numerical Python, is a fundamental library in Python for numerical computations. It provides support for working with arrays and matrices of data efficiently

In [12]:
import numpy as np
from pprint import pprint

## Basic

In [125]:
array = np.array ( [1,2,3,4,5] )
matrix = np.array ( [
  [1,2,3,4,5],
  [6,7,8,9,0]
] )

pprint (array)
pprint (matrix)

pprint (f"Array Shape {array.shape}")
pprint (f"Matrix Shape {matrix.shape}")

array([1, 2, 3, 4, 5])
array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])
'Array Shape (5,)'
'Matrix Shape (2, 5)'


## Understanding Numpy Universal Functions (`ufuncs`)

Ufuncs are a key feature of NumPy, designed to perform element - wise operations on arrays with remarkable efficiency.  At their core, ufuncs are a type of function implemented in C that can operate on arrays, broadcasting the operation if necessary.  These functions are designed to work seamlessly with arrays of various sizes and dimensions, making them a versatile tool for mathematical and numerical operations.

**Key Advantages of `ufuncs`**: Ufuncs offer several notable advantages
- *Speed*: Ufuncs are highly optimized, often faster than 
equivalent Python code with loops. The C implementation 
ensures efficient computation
- *Convenience*: They provide a concise and convenient way to 
express mathematical operations on arrays, eliminating the need 
for explicit loops
- *Broadcasting*: Ufuncs automatically handle broadcasting, 
allowing operations on arrays of different shapes, which greatly 
simplifies code

In [16]:
# creating a custom ufunc
def custom_function ( x ):
  return ( x + 1 )**2

# nin => numero de parametros de entrada
# nout => numero de parametros de salida 
custom_ufunc = np.frompyfunc (
  custom_function, 
  nin=1, 
  nout=1
)

N = 10
array = np.array ( [i for i in range (N+1)] )
result = custom_ufunc (array)

pprint (array)
pprint (result)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121], dtype=object)


## Arithmetic and Math Basic

In [ ]:
N0 = 1
N1 = 10
a1 = np.array ( [2**i for i in range (N0,N1)] )
a2 = np.array ( [j**2 for j in range (N0,N1)] )

pprint ('Perform arithmetic operations')

print ('\nSum')
pprint (a1+a2)
pprint (np.add (a1,a2))

print ('\nSubtract')
pprint (a1-a2)
pprint (np.subtract (a1,a2))

print ('\nMultiply')
pprint (a1*a2)
pprint (np.multiply (a1,a2))

print ('\nDivide')
pprint (a1/a2)
pprint (np.divide(a1,a2))
pprint (a1//a2)

'Perform arithmetic operations'

Sum
array([  3,   8,  17,  32,  57, 100, 177, 320, 593])
array([  3,   8,  17,  32,  57, 100, 177, 320, 593])

Subtract
array([  1,   0,  -1,   0,   7,  28,  79, 192, 431])
array([  1,   0,  -1,   0,   7,  28,  79, 192, 431])

Multiply
array([    2,    16,    72,   256,   800,  2304,  6272, 16384, 41472])
array([    2,    16,    72,   256,   800,  2304,  6272, 16384, 41472])

Divide
array([2.        , 1.        , 0.88888889, 1.        , 1.28      ,
       1.77777778, 2.6122449 , 4.        , 6.32098765])
array([2.        , 1.        , 0.88888889, 1.        , 1.28      ,
       1.77777778, 2.6122449 , 4.        , 6.32098765])
array([2, 1, 0, 1, 1, 1, 2, 4, 6])


In [52]:
N = 10
A = 15
decimals = 2
array = np.array ( [(i**2)/A for i in range (N)] )

pprint (array)

pprint ("Round elements to the nearest integer")
rounded = np.round (array, decimals=decimals)
pprint (rounded)

pprint ("Round down to the nearest integer")
floor = np.round (array, decimals=decimals)
pprint (floor)

pprint ("Round up to the nearest integer")
ceil = np.ceil (array)
pprint (ceil)

array([0.        , 0.06666667, 0.26666667, 0.6       , 1.06666667,
       1.66666667, 2.4       , 3.26666667, 4.26666667, 5.4       ])
'Round elements to the nearest integer'
array([0.  , 0.07, 0.27, 0.6 , 1.07, 1.67, 2.4 , 3.27, 4.27, 5.4 ])
'Round down to the nearest integer'
array([0.  , 0.07, 0.27, 0.6 , 1.07, 1.67, 2.4 , 3.27, 4.27, 5.4 ])
'Round up to the nearest integer'
array([0., 1., 1., 1., 2., 2., 3., 4., 5., 6.])


In [54]:
N = 10
A = 2
array = np.array ( [ ((i + 1)**A + A*i) for i in range(N) ] )
ln_natural = np.log (array)
ln_10 = np.log10 (array)

pprint (f"Natural Logarithm: { np.round(ln_natural,2) }")
pprint (f"Base 10 Logarithm: { np.round(ln_10,2) }")

'Natural Logarithm: [0.   1.79 2.56 3.09 3.5  3.83 4.11 4.36 4.57 4.77]'
'Base 10 Logarithm: [0.   0.78 1.11 1.34 1.52 1.66 1.79 1.89 1.99 2.07]'


In [ ]:
N = 100

array = np.array ( [i for i in range(N+1)] )

def sum_function ( n:int ):
  return (n*(n+1))/2

assert sum_function(n=N) == np.sum(array)

pprint (f"Cumulative sum => {np.cumsum(array)[0:10]}")

'Cumulative sum [ 0  1  3  6 10 15 21 28 36 45]'


In [64]:
N = 10

array = np.array ( [i for i in range (1,N+1)] )

product = np.prod (array)
cumulative_product = np.cumprod (array)

pprint (f"Total Product: {product}")
pprint (f"Cumulative Product: {cumulative_product[0:5]}")

'Total Product: 3628800'
'Cumulative Product: [  1   2   6  24 120]'


In [ ]:
N = 100
N0 = 10
N1 = 20

array = np.random.randint(low=N0, high=N1, size=N) 
pprint (array)

# finding the lcm (least common multiple)
pprint (f"LCM: {np.lcm.reduce(array)}")

# finding the gcd (greatest common divisor)
pprint (f"GCD: {np.gcd.reduce(array)}")

array([16, 12, 15, 13, 11, 11, 14, 19, 16, 15, 16, 14, 19, 11, 19, 16, 13,
       10, 12, 17, 16, 19, 10, 19, 14, 15, 10, 10, 15, 13, 12, 16, 12, 11,
       12, 14, 10, 16, 16, 11, 13, 14, 12, 12, 17, 11, 14, 10, 10, 11, 19,
       16, 18, 16, 19, 14, 14, 14, 16, 15, 13, 13, 19, 18, 19, 14, 13, 10,
       11, 10, 16, 12, 10, 13, 11, 14, 19, 19, 16, 12, 19, 11, 17, 18, 15,
       14, 17, 11, 16, 12, 12, 12, 17, 15, 15, 12, 18, 10, 10, 15])
'LCM: 232792560'
'Total Product: 0'
'GCD: 1'


In [110]:
N = 5
array = np.array( [i for i in range(N)] )

sinh = np.sinh (array)
cosh = np.cosh (array)

pprint (f"Hyperbolic Sine: {np.round(sinh,2)}")
pprint (f"Hyperbolic Cosine: {np.round(cosh,2)}")

'Hyperbolic Sine: [ 0.    1.18  3.63 10.02 27.29]'
'Hyperbolic Cosine: [ 1.    1.54  3.76 10.07 27.31]'


In [123]:
N = 10
N0 = 0
N1 = 20
M = 10
M0 = 10
M1 = 30

array1 = np.random.randint (N0,N1,N)
array2 = np.random.randint (M0,M1,M)

pprint (array1)
pprint (array2)

union = np.union1d (array1,array2)
intersection = np.intersect1d (array1,array2)
difference = np.setdiff1d (array1,array2)

pprint (f"Union: {union}")
pprint (f"Intersection: {intersection}")
pprint (f"Difference Set: {difference}")

array([ 0, 11,  6, 16,  9, 17, 13, 10,  8,  5])
array([14, 16, 13, 21, 20, 22, 20, 18, 22, 11])
'Union: [ 0  5  6  8  9 10 11 13 14 16 17 18 20 21 22]'
'Intersection: [11 13 16]'
'Difference Set: [ 0  5  6  8  9 10 17]'


## Mastery in Numpy

In [ ]:

N = 100_000

array = np.array( [i for i in range(N)] )
outer = np.outer(array,array)
pprint (array.shape)
pprint (outer.shape)

In [178]:
# solve a system of linear equations with multiple variables

A = np.array([
  [2,1,-1],
  [1,3,2],
  [1,0,3]
])
b = np.array( [8,13,6] )

x = np.linalg.solve(A,b)
pprint (f"Solution: {x}")

'Solution: [3.15 2.65 0.95]'


In [177]:
# generate a random symmetric matrix and find its eigenvalues and eigenvectors

symmetric_matrix = np.random.rand(4,4)
symmetric_matrix = (symmetric_matrix + symmetric_matrix.T) // 2

eigenvalues, eigenvectors = np.linalg.eig(symmetric_matrix)
print (f"Eigenvalues: {eigenvalues}")
print (f"Eigenvectors:\n{eigenvectors}")

Eigenvalues: [0. 0. 0. 0.]
Eigenvectors:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [173]:
# create a simple 3D array and calculate the mean along specified axes

three_dimensional = np.array ( [
  [
    [1,2],
    [3,4]
  ],
  [
    [5,6],
    [7,8]
  ]
])

mean_along_axis0 = np.mean (three_dimensional,axis=0)
mean_along_axis1 = np.mean (three_dimensional,axis=1)
mean_along_axis2 = np.mean (three_dimensional,axis=2)

print (f"""
Mean along Axis 0: {mean_along_axis0}
Mean along Axis 1: {mean_along_axis1}
Mean along Axis 2: {mean_along_axis2}
""")


Mean along Axis 0: [[3. 4.]
 [5. 6.]]
Mean along Axis 1: [[2. 3.]
 [6. 7.]]
Mean along Axis 2: [[1.5 3.5]
 [5.5 7.5]]



In [172]:
# calculate the element - wise square root of a 2D array and handle negative values

def transform_negative_and_calculate_sqrt (array):
  array[array < 0] = 0
  sqrt = np.sqrt(array)
  return sqrt

matrix = np.array ( [ [1,4,100,3],[-1,0,4,2] ] )
pprint (transform_negative_and_calculate_sqrt(matrix))

array([[ 1.        ,  2.        , 10.        ,  1.73205081],
       [ 0.        ,  0.        ,  2.        ,  1.41421356]])


In [170]:
# calculate the determinant of a 2D matrix and check if its invertible

matrix = np.array ( [
  [2,1],
  [1,3]
] )

determinant = np.linalg.det (matrix)
print (f"""
Determinant: {determinant}
Is Invertible: {determinant != 0}
""")


Determinant: 5.000000000000001
Is Invertible: True



In [169]:
# calculate the element - wise reciprocal of a 2D array and handle zero values

matrix = np.array ( [
  [1,2],
  [0,3],
  [0,0]
] )

reciprocal = np.where (array != 0, 1 / array, np.inf)
pprint (reciprocal)

array([       inf, 0.25      ,        inf,        inf,        inf,
       1.        , 0.33333333, 0.5       , 1.        , 1.        ])


C:\Users\Zkorpion\AppData\Local\Temp\ipykernel_11896\3231233310.py:9: RuntimeWarning: divide by zero encountered in divide
  reciprocal = np.where (array != 0, 1 / array, np.inf)


In [168]:
# create a masked array to handle invalid values in a 1D array
N = 10
MIN = 0
MAX = 5
X = 0

array = np.random.randint (MIN,MAX,N)
mask = array == X

pprint (array)
pprint (mask)

masked = np.ma.masked_where(mask,array)
pprint (masked)
pprint (type(masked))

array([0, 4, 0, 0, 0, 1, 3, 2, 1, 1])
array([ True, False,  True,  True,  True, False, False, False, False,
       False])
masked_array(data=[--, 4, --, --, --, 1, 3, 2, 1, 1],
             mask=[ True, False,  True,  True,  True, False, False, False,
                   False, False],
       fill_value=999999)
<class 'numpy.ma.core.MaskedArray'>


In [159]:
# calculate the element - wise cosine similarity between rows in a 2D array 

from scipy.spatial.distance import cosine

matrix = np.array ( [
  [1,2,3],
  [4,5,6],
  [7,8,9]
] )

cosine_similarity = np.zeros ( (matrix.shape[0],matrix.shape[1]) )

for i in range(matrix.shape[0]):
  for j in range(i, matrix.shape[1]):
    similarity = 1 - cosine( matrix[i],matrix[j] )
    cosine_similarity[i,j] = similarity
    cosine_similarity[j,i] = similarity

pprint ("Cosine Similarity Matrix")
pprint (cosine_similarity)

'Cosine Similarity Matrix'
array([[1.        , 0.97463185, 0.95941195],
       [0.97463185, 1.        , 0.99819089],
       [0.95941195, 0.99819089, 1.        ]])


In [155]:
# generate a random permutation of integers within a specified range

N = 10
permutation = np.random.permutation ( np.arange(1,N+1) )
pprint (permutation)

array([ 2,  6,  9,  8,  7,  4,  3, 10,  1,  5])


In [ ]:
# calculate the element - wise reciprocal of a 3D array and handle zero values

def reciprocal_with_zero_handling (array):
  array[array == 0] = 1e-10
  print (array)
  reciprocal = 1 / array
  return reciprocal

tensor = np.array ( [
  [
    [8.0,6.0,4.0,2.0,0],
    [1.0,3.0,2.0,7.0,0]
  ],
  [
    [0,2.0,4.0,6.0,8.0],
    [1.0,0,5.0,7.0,9.0]
  ]
] )

reciprocal_tensor = reciprocal_with_zero_handling (tensor)
pprint (reciprocal_tensor)

[[[8.e+00 6.e+00 4.e+00 2.e+00 1.e-10]
  [1.e+00 3.e+00 2.e+00 7.e+00 1.e-10]]

 [[1.e-10 2.e+00 4.e+00 6.e+00 8.e+00]
  [1.e+00 1.e-10 5.e+00 7.e+00 9.e+00]]]
array([[[1.25000000e-01, 1.66666667e-01, 2.50000000e-01, 5.00000000e-01,
         1.00000000e+10],
        [1.00000000e+00, 3.33333333e-01, 5.00000000e-01, 1.42857143e-01,
         1.00000000e+10]],

       [[1.00000000e+10, 5.00000000e-01, 2.50000000e-01, 1.66666667e-01,
         1.25000000e-01],
        [1.00000000e+00, 1.00000000e+10, 2.00000000e-01, 1.42857143e-01,
         1.11111111e-01]]])


In [ ]:
# create a mask for values within a specified range in a 2D array and calculate their sum

matrix = np.array ( [
  [1,2,3],
  [4,5,6],
  [7,8,9]
] )

min_value = 3
max_value = 7

mask = (matrix <= max_value) & (min_value <= matrix)
pprint (mask)

sum_of_masked_values = np.sum (matrix[mask])
pprint (sum_of_masked_values)

array([[False, False,  True],
       [ True,  True,  True],
       [ True, False, False]])
25


## Referencias

- NumPy Mastery: 150 Practical Examples in Python
- 

# 